[network]
    peers = ["127.0.0.1:20200", "127.0.0.1:20201", "127.0.0.1:20202", "127.0.0.1:20203", "127.0.0.1:20204"]

[account]
    account_type = 0
    account_file_type = 1
    account_file = "../bin/accounts/client0.keystore"  # 从 mytest 出发，到上级目录的 bin 文件夹
    account_password = ""

[chain]
    chain_id = "chain0"
    group_id = "group0"

[log]
level = "info"